version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: apostol
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: finance
    networks:
      - finance-net

  web:
    image: apostol-finance
    container_name: finance-apostol
    volumes:
      - ./finance_project:/app
    ports:
      - "8000:8000"
    networks:
      - finance-net
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: finance
      DB_USER: apostol
      DB_PASSWORD: 1
    command: python /app/manage.py runserver

networks:
  finance-net:

volumes:
  postgres-data:
